### ISSUE TITLE
Can you support Japanese?

### ISSUE THREAD

**Issue by kyohei103** [BarneyCompiler/AstraClientEagler#2]
Hi BarneyCompiler. 
I love your project, but I have a problem.
Japanese doesn't work.
Can you support Japanese?
Thanks.

**Comment by radmanplays** [comment]
this will be supported soon

**Comment by kyohei103** [comment]
Thank you!

**Comment by radmanplays** [comment]
japanese support has been added! https://barneycompiler.github.io/AstraClientEagler/javascript

**Comment by kyohei103** [comment]
Arigatou!
You've also supported other languages.
Emoji in places, but it has a good feel.
Thank for support japanese!
